name: Build
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # Needed to write to GitHub draft release

env:
  RONIN_VERSION: ${{ github.ref_name }}

jobs:
  build-ronin:
    runs-on: ubuntu-20.04
    steps:
      - name: Download compiled launcher
        run:
          wget "https://github.com/TF2SR/RoninLauncher/releases/download/${{ env.RONIN_VERSION }}/ronin-launcher.zip"
      - name: Checkout release files
        uses: actions/checkout@v3
        with:
          ref: ${{ env.RONIN_VERSION }}
          path: ronin
      - name: Checkout core mods
        uses: actions/checkout@v3
        with:
          repository: TF2SR/RoninMods
          ref: ${{ env.RONIN_VERSION }}
          path: ronin-mods
      - name: Update mod version info
        run: |
          export MOD_VERSION=$(echo $RONIN_VERSION | tr -d 'v')
          cat <<< $(jq ".Version = \"${MOD_VERSION}\"" ronin-mods/Ronin.Client/mod.json) > ronin-mods/Ronin.Client/mod.json
          cat <<< $(jq ".Version = \"${MOD_VERSION}\"" ronin-mods/Ronin.Server/mod.json) > ronin-mods/Ronin.Server/mod.json
      - name: Generate md5sum file
        working-directory: ronin-mods
        run: |
          echo -e "# Check with 'md5sum -c md5sum.txt' at the root of mods folder\n" > md5sum.txt
          git ls-tree -r $RONIN_VERSION --name-only | xargs -L1 md5sum >> md5sum.txt
      - name: Make folder structure
        run: |
          mv -v ronin/release/* ronin/.
          rm -d ronin/release
          mkdir -p ronin/R2Ronin/mods

          unzip ronin-launcher.zip -d ronin
          rsync -avr --exclude="Ronin.Coop" --exclude=".git*" ronin-mods/. ronin/R2Ronin/mods
      - name: Cleanup root Ronin repository files
        working-directory: ronin
        run: |
          rm -rf .git .github .gitignore *.md LICENSE thunderstore .ci.env.example r2ds.bat wsock32.dll assets
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Ronin.release.${{ env.RONIN_VERSION }}
          path: ronin
      - name: Create zip to upload
        run: |
          cd ronin/
          zip --recurse-paths --quiet Ronin.release.${{ env.RONIN_VERSION }}.zip .
          mv Ronin.release.${{ env.RONIN_VERSION }}.zip ../
      - name: Compute SHA-512 checksum
        run: |
          sha512sum Ronin.release.${{ env.RONIN_VERSION }}.zip
      - name: Upload zip to release draft
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v') && !contains(env.RONIN_VERSION, '-rc')
        with:
          draft: true
          files: Ronin.release.${{ env.RONIN_VERSION }}.zip
